AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-bedrock

  Sample SAM Template for sam-bedrock

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  BedrockSlackAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: bedrock-slack-app-function
      CodeUri: bedrock-slack-app/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
      - x86_64
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      MemorySize: 512
      Timeout: 900
      Policies:
        - Version: '2012-10-17' # IAM ポリシーのバージョン
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: "*"
        - Version: '2012-10-17'
          Statement:
            - Sid: 'BedrockScopedAccess'
              Effect: 'Allow'
              Action: 'bedrock:InvokeModelWithResponseStream'
              Resource:
                  - 'arn:aws:bedrock:*::foundation-model/anthropic.claude-v2:1'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - bedrock:Retrieve
              Resource: 'arn:aws:bedrock:us-east-1:233928981508:knowledge-base/'
    
      # Events:
      #   HelloWorld:
      #     Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
      #     Properties:
      #       Path: /hello
      #       Method: get

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: API Gateway endpoint URL for Prod stage for Hello World function
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  BedrockSlackAppFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt BedrockSlackAppFunction.Arn
  BedrockSlackAppFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt BedrockSlackAppFunctionRole.Arn
